{
  # self,
  pkgs,
  config,
  lib,
  ...
}: let
  user = "tmp";
in {
  theme.name = "catppuccin-mocha";

  # programs.ghostty.enable = true;
  programs.foot = {
    enable = true;
    enableBashIntegration = true;
  };
  programs.helix.enable = true;
  # programs.hyprland.enable = true;
  programs.dwl.enable = true;

  programs.greetd = {
    enable = true;
    command = pkgs.dwl;
  };

  users = {
    # mutableUsers = false;
    users."${user}" = {
      home = "/home/${user}";
      description = user;
      shell = pkgs.bash;
      isNormalUser = true;
      extraGroups = [ "wheel" "networkmanager" ];
      hashedPassword = "$y$j9T$SLZhlPDME3Dz/8yrAWV.P0$41gHdK02BiDHeATkV0ANls3KtDJF8aIpmqx1RnFHaX8";
      homeless = true;
    };
  };
  programs.bash.enable = true;

  boot = {
    initrd.availableKernelModules = [ "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod" ];
    initrd.kernelModules = [];
    kernelModules = [ "kvm-intel" "wl" ];
    extraModulePackages = [ config.boot.kernelPackages.broadcom_sta ];
    loader = {
      grub.enable = false;
      systemd-boot.enable = true;
      efi.canTouchEfiVariables = true;
    };
  };
  networking.useDHCP = lib.mkDefault true;
  networking.networkmanager = {
    enable = true;
    wifi.backend = "iwd";
  };
  hardware.cpu.intel.updateMicrocode = true;
  hardware.enableRedistributableFirmware = true;
  system.stateVersion = "25.05";

  nixpkgs.config.permittedInsecurePackages = [
    "broadcom-sta-6.30.223.271-57-6.12.43"
  ];

  environment.systemPackages = [
    pkgs.custom.hello
  ];

  # awful right... the stuff below was generated by nixos-generate-config
  # and is purely temporary until I daily drive this new config :)
  fileSystems."/" = {
    device = "/dev/disk/by-uuid/802b02cf-a88f-43ff-b13f-78c0e898c63b";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/6CA9-BC70";
    fsType = "vfat";
    options = [ "fmask=0077" "dmask=0077" ];
  };

  swapDevices = [];
}
